
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

isy994:
  host: !secret isy_host
  username: !secret isy_user
  password: !secret isy_password

# Harmony Hub - Upstairs
remote:
  - platform: harmony
    name: Game Room
    host: !secret harmony_gameroom_ip

# Ecobee
notify:
  - name: ecobee_downstairs
    platform: ecobee
  - name: ecobee_upstairs
    platform: ecobee

roku:
  - host: !secret roku_gameroom_ip

amcrest:
  - host: !secret fp_cam_ip
    username: !secret fp_cam_user
    password: !secret fp_cam_password
    name: FP Cam
    binary_sensors:
      - motion_detected
      - online
  - host: !secret bp_cam_ip
    username: !secret bp_cam_user
    password: !secret bp_cam_password
    name: BP Cam
    binary_sensors:
      - motion_detected
      - online